export interface CountryCode {
  code: string;
  iso: string;
}

/**
 * List of worldwide calling country codes sorted in ascending numerical order (+1 to +998).
 * Used across Visa Application Modal and Package Booking Modal.
 */
export const COUNTRY_CODES: CountryCode[] = [
  { code: "+1",   iso: "US" },
  { code: "+1",   iso: "CA" },
  { code: "+1",   iso: "JM" },
  { code: "+1",   iso: "TT" },
  { code: "+1",   iso: "BB" },
  { code: "+1",   iso: "BS" },
  { code: "+7",   iso: "RU" },
  { code: "+7",   iso: "KZ" },
  { code: "+20",  iso: "EG" },
  { code: "+27",  iso: "ZA" },
  { code: "+30",  iso: "GR" },
  { code: "+31",  iso: "NL" },
  { code: "+32",  iso: "BE" },
  { code: "+33",  iso: "FR" },
  { code: "+34",  iso: "ES" },
  { code: "+36",  iso: "HU" },
  { code: "+39",  iso: "IT" },
  { code: "+40",  iso: "RO" },
  { code: "+41",  iso: "CH" },
  { code: "+43",  iso: "AT" },
  { code: "+44",  iso: "GB" },
  { code: "+45",  iso: "DK" },
  { code: "+46",  iso: "SE" },
  { code: "+47",  iso: "NO" },
  { code: "+48",  iso: "PL" },
  { code: "+49",  iso: "DE" },
  { code: "+51",  iso: "PE" },
  { code: "+52",  iso: "MX" },
  { code: "+53",  iso: "CU" },
  { code: "+54",  iso: "AR" },
  { code: "+55",  iso: "BR" },
  { code: "+56",  iso: "CL" },
  { code: "+57",  iso: "CO" },
  { code: "+58",  iso: "VE" },
  { code: "+60",  iso: "MY" },
  { code: "+61",  iso: "AU" },
  { code: "+62",  iso: "ID" },
  { code: "+63",  iso: "PH" },
  { code: "+64",  iso: "NZ" },
  { code: "+65",  iso: "SG" },
  { code: "+66",  iso: "TH" },
  { code: "+81",  iso: "JP" },
  { code: "+82",  iso: "KR" },
  { code: "+84",  iso: "VN" },
  { code: "+86",  iso: "CN" },
  { code: "+90",  iso: "TR" },
  { code: "+91",  iso: "IN" },
  { code: "+92",  iso: "PK" },
  { code: "+93",  iso: "AF" },
  { code: "+94",  iso: "LK" },
  { code: "+95",  iso: "MM" },
  { code: "+98",  iso: "IR" },
  { code: "+212", iso: "MA" },
  { code: "+213", iso: "DZ" },
  { code: "+216", iso: "TN" },
  { code: "+218", iso: "LY" },
  { code: "+220", iso: "GM" },
  { code: "+221", iso: "SN" },
  { code: "+222", iso: "MR" },
  { code: "+223", iso: "ML" },
  { code: "+224", iso: "GN" },
  { code: "+225", iso: "CI" },
  { code: "+226", iso: "BF" },
  { code: "+227", iso: "NE" },
  { code: "+228", iso: "TG" },
  { code: "+229", iso: "BJ" },
  { code: "+230", iso: "MU" },
  { code: "+231", iso: "LR" },
  { code: "+232", iso: "SL" },
  { code: "+233", iso: "GH" },
  { code: "+234", iso: "NG" },
  { code: "+235", iso: "TD" },
  { code: "+236", iso: "CF" },
  { code: "+237", iso: "CM" },
  { code: "+238", iso: "CV" },
  { code: "+239", iso: "ST" },
  { code: "+240", iso: "GQ" },
  { code: "+241", iso: "GA" },
  { code: "+242", iso: "CG" },
  { code: "+243", iso: "CD" },
  { code: "+244", iso: "AO" },
  { code: "+245", iso: "GW" },
  { code: "+248", iso: "SC" },
  { code: "+249", iso: "SD" },
  { code: "+250", iso: "RW" },
  { code: "+251", iso: "ET" },
  { code: "+252", iso: "SO" },
  { code: "+253", iso: "DJ" },
  { code: "+254", iso: "KE" },
  { code: "+255", iso: "TZ" },
  { code: "+256", iso: "UG" },
  { code: "+257", iso: "BI" },
  { code: "+258", iso: "MZ" },
  { code: "+260", iso: "ZM" },
  { code: "+261", iso: "MG" },
  { code: "+263", iso: "ZW" },
  { code: "+264", iso: "NA" },
  { code: "+265", iso: "MW" },
  { code: "+266", iso: "LS" },
  { code: "+267", iso: "BW" },
  { code: "+268", iso: "SZ" },
  { code: "+269", iso: "KM" },
  { code: "+291", iso: "ER" },
  { code: "+351", iso: "PT" },
  { code: "+352", iso: "LU" },
  { code: "+353", iso: "IE" },
  { code: "+354", iso: "IS" },
  { code: "+356", iso: "MT" },
  { code: "+357", iso: "CY" },
  { code: "+358", iso: "FI" },
  { code: "+359", iso: "BG" },
  { code: "+370", iso: "LT" },
  { code: "+371", iso: "LV" },
  { code: "+372", iso: "EE" },
  { code: "+373", iso: "MD" },
  { code: "+374", iso: "AM" },
  { code: "+375", iso: "BY" },
  { code: "+380", iso: "UA" },
  { code: "+381", iso: "RS" },
  { code: "+382", iso: "ME" },
  { code: "+385", iso: "HR" },
  { code: "+386", iso: "SI" },
  { code: "+387", iso: "BA" },
  { code: "+389", iso: "MK" },
  { code: "+420", iso: "CZ" },
  { code: "+421", iso: "SK" },
  { code: "+501", iso: "BZ" },
  { code: "+502", iso: "GT" },
  { code: "+503", iso: "SV" },
  { code: "+504", iso: "HN" },
  { code: "+505", iso: "NI" },
  { code: "+506", iso: "CR" },
  { code: "+507", iso: "PA" },
  { code: "+509", iso: "HT" },
  { code: "+591", iso: "BO" },
  { code: "+592", iso: "GY" },
  { code: "+593", iso: "EC" },
  { code: "+595", iso: "PY" },
  { code: "+597", iso: "SR" },
  { code: "+598", iso: "UY" },
  { code: "+673", iso: "BN" },
  { code: "+674", iso: "NR" },
  { code: "+675", iso: "PG" },
  { code: "+676", iso: "TO" },
  { code: "+677", iso: "SB" },
  { code: "+678", iso: "VU" },
  { code: "+679", iso: "FJ" },
  { code: "+680", iso: "PW" },
  { code: "+685", iso: "WS" },
  { code: "+686", iso: "KI" },
  { code: "+688", iso: "TV" },
  { code: "+691", iso: "FM" },
  { code: "+692", iso: "MH" },
  { code: "+855", iso: "KH" },
  { code: "+856", iso: "LA" },
  { code: "+880", iso: "BD" },
  { code: "+960", iso: "MV" },
  { code: "+961", iso: "LB" },
  { code: "+962", iso: "JO" },
  { code: "+963", iso: "SY" },
  { code: "+964", iso: "IQ" },
  { code: "+965", iso: "KW" },
  { code: "+966", iso: "SA" },
  { code: "+967", iso: "YE" },
  { code: "+968", iso: "OM" },
  { code: "+970", iso: "PS" },
  { code: "+971", iso: "AE" },
  { code: "+972", iso: "IL" },
  { code: "+973", iso: "BH" },
  { code: "+974", iso: "QA" },
  { code: "+975", iso: "BT" },
  { code: "+977", iso: "NP" }, // Nepal default
  { code: "+992", iso: "TJ" },
  { code: "+993", iso: "TM" },
  { code: "+994", iso: "AZ" },
  { code: "+995", iso: "GE" },
  { code: "+996", iso: "KG" },
  { code: "+998", iso: "UZ" },
];

/**
 * Converts ISO 2-letter country code -> Unicode flag emoji (e.g. "NP" -> "🇳🇵")
 */
export const isoToFlag = (iso: string): string =>
  iso
    .toUpperCase()
    .replace(/./g, (char) =>
      String.fromCodePoint(127397 + char.charCodeAt(0))
    );
